ALTER TABLE `locacamera_customer_profiles`
  ADD COLUMN `cpf_cnpj` varchar(32) NULL AFTER `estoquenow_client_id`,
  ADD COLUMN `rg_number` varchar(64) NULL AFTER `cpf_cnpj`,
  ADD COLUMN `rg_issue_agency` varchar(64) NULL AFTER `rg_number`,
  ADD COLUMN `social_name` varchar(255) NULL AFTER `rg_issue_agency`,
  ADD COLUMN `state_registration` varchar(64) NULL AFTER `social_name`,
  ADD COLUMN `municipal_registration` varchar(64) NULL AFTER `state_registration`,
  ADD COLUMN `birthday` date NULL AFTER `municipal_registration`,
  ADD COLUMN `gender` varchar(32) NULL AFTER `birthday`,
  ADD COLUMN `gender_name` varchar(64) NULL AFTER `gender`,
  ADD COLUMN `is_foreigner` boolean NULL AFTER `gender_name`,
  ADD COLUMN `phone_country_code` varchar(8) NULL AFTER `is_foreigner`,
  ADD COLUMN `phone2` varchar(50) NULL AFTER `phone_country_code`,
  ADD COLUMN `phone2_country_code` varchar(8) NULL AFTER `phone2`,
  ADD COLUMN `phone_type` varchar(32) NULL AFTER `phone2_country_code`,
  ADD COLUMN `phone2_type` varchar(32) NULL AFTER `phone_type`,
  ADD COLUMN `address_type` varchar(32) NULL AFTER `phone2_type`,
  ADD COLUMN `address_neighborhood` varchar(255) NULL AFTER `address_type`,
  ADD COLUMN `address_state` varchar(64) NULL AFTER `address_neighborhood`,
  ADD COLUMN `address_number` varchar(64) NULL AFTER `address_state`,
  ADD COLUMN `address_complement` varchar(255) NULL AFTER `address_number`,
  ADD COLUMN `status_id` varchar(64) NULL AFTER `address_complement`,
  ADD COLUMN `status_name` varchar(128) NULL AFTER `status_id`,
  ADD COLUMN `is_enabled` boolean NULL AFTER `status_name`,
  ADD COLUMN `is_blocked` boolean NULL AFTER `is_enabled`,
  ADD COLUMN `standard_discount` decimal(10,4) NULL AFTER `is_blocked`,
  ADD COLUMN `customer_profile` varchar(255) NULL AFTER `standard_discount`,
  ADD COLUMN `customer_profile_name` varchar(255) NULL AFTER `customer_profile`,
  ADD COLUMN `user_contact` varchar(255) NULL AFTER `customer_profile_name`,
  ADD COLUMN `traffic_source_id` varchar(64) NULL AFTER `user_contact`,
  ADD COLUMN `type_name` varchar(64) NULL AFTER `traffic_source_id`,
  ADD COLUMN `legacy_data` json NULL AFTER `pinned_files`,
  ADD KEY `locacamera_customer_profiles_store_cpf_cnpj_idx` (`store_id`, `cpf_cnpj`),
  ADD CONSTRAINT `locacamera_customer_profiles_customer_fk`
    FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`) ON DELETE CASCADE,
  ADD CONSTRAINT `locacamera_customer_profiles_store_fk`
    FOREIGN KEY (`store_id`) REFERENCES `stores` (`id`) ON DELETE CASCADE;
